### ISSUE TITLE
Figure out what 'home' is

### ISSUE THREAD

**Issue by rknizzle** [rknizzle/propermesh-view#13]
I want the propermesh logo at the top left of the site to bring you back to the home page but I also have to decide like what the 'home' page is. If its the landing page or if its the page you go to after you login or if it depends on your current login state

**Comment by ErikAmerico** [comment]
In my last commit, I added navigation to the propermesh logo that brings you back to the landing page. I know you're still mulling this over, but in the meantime its a nice way to get back to the landing page instead of having to go to the address bar to manually navigate back

**Comment by rknizzle** [comment]
I think my plan is for the propermesh logo to always go back to the landing page and then Ill add some sort of button on the landing page to go to the app/analysis page
