### ISSUE TITLE
Thickness Analysis Box (Analysis Page)

### ISSUE THREAD

**Issue by rknizzle** [rknizzle/propermesh-view#29]
You can see the sketch of the thickness analysis box in the figma.

The starting and polling of the results will work the same way in this component. 

Theres just an added complexity of having a 'threshold' input. So where the geometry analysis could only be done once per part, there can be many different thickness analyses with different thresholds for a single part.

So there will need to be a UI to enter a threshold  before pressing start. There will also need to be visual rows so that a user can select a previously run analysis to see the results
![thick-box](https://github.com/rknizzle/propermesh-view/assets/40612461/0122de3a-c2ce-4c34-beca-0f61cb184ffa)

So when you first load in a part none of those boxes with the numbers will be in there but as you enter a threshold and press start it will be created with the threshold value.

Im thinking if the threshold value is modified it should clear the results of the previous analysis and if they press start again with a new threshold itll create a new box with the threshold for the second analysis.

Let me know if you have questions or want to work together on this

**Comment by rknizzle** [comment]
@ErikAmerico Let me know if you need any clarification on anythng in the thickness analysis box

**Comment by ErikAmerico** [comment]
@rknizzle Does the range of the Threshold go from 0.0 to 1.0?

**Comment by rknizzle** [comment]
> @rknizzle Does the range of the Threshold go from 0.0 to 1.0?

No it's just a millimeter value with no real limit. More than one decimal place is currently supported too. Maybe add a limit of being able to enter 2 decimal places.


AKA
0.07 valid
1.37 valid

And then maybe you can limit the input box to stop at 1.37 and not let them enter something like 1.375

**Comment by rknizzle** [comment]
@ErikAmerico Actually now that I think about it; if a user is able to enter a value like 1999.99 then that might not fit in my little cubes in my UI sketch so we might have to stretch them out to be rectangles and maybe have multiple rows if needed

**Comment by ErikAmerico** [comment]
Roger that! 

I'll try out a few things.

**Comment by rknizzle** [comment]
@ErikAmerico Oh ya one more thing lol. The backend doesn't currently return the percentage of thin area so that field wont need to be in the UI for this first version.

Heres an example of the output:
```
{
    "id": "aacf7c26-4d1b-4477-8d9f-d94f5b143884",
    "threshold": 0.7,
    "is_thin": true,
    "thin_surface_area": 2.0,
    "status": "complete",
    "part_id": "5d098cac-7978-4db5-b301-6415180cd664",
    "units": "mm",
    "failure_reason": null
}
```

So show the `thin_surface_area` value in the `Thin surface area:` field and then if `is_thin` == true, have the red text saying `Thin areas detected`. If is_thin == false then maybe have green text saying `No thin areas detected`

**Comment by ErikAmerico** [comment]
@rknizzle Does the thickness analysis require that you select mm or inches from the units selector?

**Comment by rknizzle** [comment]
> @rknizzle Does the thickness analysis require that you select mm or inches from the units selector?

Yes I forgot to mention that. It will fail unless the part has a 'units' value

**Comment by ErikAmerico** [comment]
Nice, yeah I noticed that and was hoping that was the case!

**Comment by ErikAmerico** [comment]
I still have to create a second row for the threshold history values to hang out in.

But I think this is looking pretty good otherwise, 

Unless I'm forgetting something
