### ISSUE TITLE
Each thickness analysis results need to also have the context of which units were used as well

### ISSUE THREAD

**Issue by rknizzle** [rknizzle/propermesh-view#44]
A thickness analysis is based on a threshold and the units of the part. So for example, a thickness analysis could be done with a threshold of 0.1 and units of mm and then also an analysis with a threshold of 0.1 and a units of inches. 

Currently the UI doesn't allow you to do a thickness analysis of 0.1 in mm and then switch to inches and then run another analysis with a 0.1 threshold. The scenario for this could be that a user uploads a file and selects inches and then runs the analysis and then realizes they made a mistake and switches units to mm but then they wont be able to run the 0.1 analysis in mm.

So if we fix this and allow a thickness analysis to be done in 0.1 in both mm and inches then there would be no way of differentiation them in these boxes in the UI:
![threhsold-boxes](https://github.com/rknizzle/propermesh-view/assets/40612461/56bb23ce-e24e-4b2e-a5ba-e6bbacfb34d6)

I think the easiest solution to this is to allow thickness analysis to start with the same threshold of an existing one as long as the units are different now.
And then I think the row of boxes should only show up for the units that are currently selected and not for both types of units.

So like there would be a separate row of boxes showing depending on which units you have selected

**Comment by ErikAmerico** [comment]
Understood!!

**Comment by rknizzle** [comment]
Completed in https://github.com/rknizzle/propermesh-view/pull/45
