### ISSUE TITLE
Make hamburger menu options all in the menu or all on the header (on mobile)

### ISSUE THREAD

**Issue by rknizzle** [rknizzle/propermesh-view#52]
The menu options should either all be in burger menu or they should all be on the header and have no burger menu rather than depending on the size having some of the options on the header and some of the options in the burger menu

![hamburger-menu-both](https://github.com/rknizzle/propermesh-view/assets/40612461/0038b674-5cbf-4da5-950b-1dbd7ed178df)

This is super low priority. I'm just documenting it here.

**Comment by ErikAmerico** [comment]
This was taken care of!
